language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
matrix:
  allow_failures:
    - python: "2.7"
sudo: required
dist: trusty
cache:
  directories:
    - ~/.cache/pip
install:
  - pip install --upgrade coveralls
  - pip install -r requirements.txt
  - python setup.py install
script:
  - coverage run --source mta setup.py test
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5
      - libpython3.5-dev
      - libgdal-dev
      - libproj-dev
      - python-numpy
      - python3-numpy
      - python-gdal
      - python3-gdal
after_success: coveralls
